
--------------CREACION DE TABLAS----------------
CREATE TABLE CLIENTES(
COD_CLIE INTEGER NOT NULL PRIMARY KEY,
VAL_APE1 VARCHAR(15),
VAL_APE2 VARCHAR(15),
VAL_NOM1 VARCHAR(18),
VAL_NOM2 VARCHAR(18),
COD_SEXO VARCHAR(1),
FEC_CREA TIMESTAMP,
SAL_DEUD_ANTE FLOAT(8),
FEC_NACI DATE
);

CREATE TABLE PEDIDOS(
 FEC_SOLI DATE,
 COD_PERI INTEGER,
 VAL_NUME_SOLI INTEGER PRIMARY KEY,
 FEC_FACT DATE,
 VAL_ORIG VARCHAR(9),
 COD_CLIE INTEGER,
 COD_REGI INTEGER,
 COD_ZONA INTEGER,
 COD_SECC VARCHAR(1),
 SAL_DEUD_ANTE FLOAT(7),
 VAL_MONT_ESTI FLOAT(7),
 VAL_MONT_SOLI FLOAT(7),
 VAL_ESTA_PEDI VARCHAR(10),
 MOT_RECH VARCHAR(13),
 VAL_MONT_FLET FLOAT(3),
 VAL_UNID_LBEL INTEGER,
 VAL_UNID_CYZO INTEGER,
 VAL_UNID_ESIK INTEGER
);

ALTER TABLE PEDIDOS
ADD CONSTRAINT fk_COD_CLIE 
FOREIGN KEY (COD_CLIE) REFERENCES CLIENTES(COD_CLIE) DEFERRABLE;


--------------DESHABILITACION Y HABILITACION TEMPORAL DE LA RESTRICCION DE CLAVE FORANEA----------------
ALTER TABLE PEDIDOS DISABLE CONSTRAINT fk_COD_CLIE;

ALTER TABLE PEDIDOS ENABLE CONSTRAINT fk_COD_CLIE;

--------------EJERCICIO N2----------------
--LA INSERCCION DE DATOS DE LAS TABLAS, SE IMPORTO DE EL EXCEL

--------------EJERCICIO N3----------------
BEGIN
  FOR venta IN (
    SELECT COD_ZONA, SUM(VAL_UNID_LBEL + VAL_UNID_CYZO + VAL_UNID_ESIK) AS UNIDADES, SUM(VAL_MONT_SOLI) AS MONTO_SOLICITADO
    FROM PEDIDOS
    GROUP BY COD_ZONA)
    LOOP
        DBMS_OUTPUT.PUT_LINE('COD_ZONA: ' || venta.COD_ZONA || ', UNIDADES: ' || venta.UNIDADES || ', MONTO_SOLICITADO: ' || venta.MONTO_SOLICITADO);
    END LOOP;
END;
--------------EJERCICIO N4----------------
BEGIN
  FOR seccion IN (
    SELECT COD_SECC, SUM(VAL_MONT_SOLI) AS MONTO_SOLICITADO
    FROM PEDIDOS
    GROUP BY COD_SECC
    ORDER BY MONTO_SOLICITADO DESC
    FETCH FIRST 20 ROWS ONLY)
    LOOP
    DBMS_OUTPUT.PUT_LINE('COD_SECC: ' || seccion.COD_SECC || ', MONTO_SOLICITADO: ' || seccion.MONTO_SOLICITADO);
  END LOOP;
END;

--------------EJERCICIO N5----------------
BEGIN
  FOR pedidos_alto_valor IN (
    SELECT COD_ZONA, COUNT(*) AS NUM_PEDIDOS
    FROM PEDIDOS
    WHERE VAL_MONT_ESTI > 250
    GROUP BY COD_ZONA
    ORDER BY COD_ZONA)
    LOOP
    DBMS_OUTPUT.PUT_LINE('Zona de Alto Valor - COD_ZONA: ' || pedidos_alto_valor.COD_ZONA || ', NUM_PEDIDOS: ' || pedidos_alto_valor.NUM_PEDIDOS);
  END LOOP;

DBMS_OUTPUT.PUT_LINE('-----------------------------------------------');

  FOR pedidos_bajo_valor IN (
    SELECT COD_ZONA, COUNT(*) AS NUM_PEDIDOS
    FROM PEDIDOS
    WHERE VAL_MONT_ESTI < 250
    GROUP BY COD_ZONA
    ORDER BY COD_ZONA)
    LOOP
    DBMS_OUTPUT.PUT_LINE('Zona de Bajo Valor - COD_ZONA: ' || pedidos_bajo_valor.COD_ZONA || ', NUM_PEDIDOS: ' || pedidos_bajo_valor.NUM_PEDIDOS);
  END LOOP;
END;



